import LessonLayout from '@/components/LessonLayout';
import FeeLab from '@/components/labs/FeeLab';

export default function BoardingPassLessonSendingAndReceiving() {
  return (
    <LessonLayout slug="sending-and-receiving">
          <p>You have a wallet. You've received some bitcoin. Now let's understand what's actually happening when you send and receive—and how to do it well.</p>

          <h2>Understanding Bitcoin Addresses</h2>
          <p>A Bitcoin address is like a mailbox. Anyone can drop letters (bitcoin) into it, but only the person with the key (your private key) can open it and move what's inside.</p>
          <p>Addresses look like gibberish: <code>bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh</code>. They're long strings of letters and numbers generated by your wallet. Modern wallets can encode addresses as QR codes for easy scanning.</p>
          <p>Here's the crucial part: <strong>Bitcoin addresses are public by design.</strong> You can share them freely. Posting your address online doesn't compromise your security—only your privacy. Your private key (stored safely in your wallet) is what actually controls the bitcoin sent to that address.</p>

          <h3>Address Types</h3>
          <p>Bitcoin has evolved through several address formats:</p>
          <ul>
            <li><strong>Legacy (P2PKH):</strong> Starts with "1". The original format. Still works but has higher fees and less efficiency.</li>
            <li><strong>SegWit (P2SH):</strong> Starts with "3". A transitional format from 2017 that reduced fees.</li>
            <li><strong>Native SegWit (Bech32):</strong> Starts with "bc1q". The current standard. Lower fees, better efficiency. Most modern wallets default to this.</li>
            <li><strong>Taproot (Bech32m):</strong> Starts with "bc1p". The newest format (2021). Enhanced privacy and future features. Growing adoption but not yet universal.</li>
          </ul>
          <p>For beginners: use whatever address format your wallet generates by default, which is likely native SegWit. All formats are compatible—you can send from any address type to any other address type.</p>

          <h2>Receiving Bitcoin: Step by Step</h2>
          <p>Receiving bitcoin is simple:</p>
          <ol>
            <li>Open your wallet app and tap "Receive."</li>
            <li>Your wallet generates a fresh receiving address (or displays your current one).</li>
            <li>Share this address with the sender—either the QR code (in person) or the text string (via message/email).</li>
            <li>Once the sender broadcasts the transaction, it appears in your wallet almost instantly as "unconfirmed."</li>
            <li>Miners include the transaction in a block (usually 10-60 minutes). It gains its first "confirmation."</li>
            <li>Each subsequent block adds another confirmation. After 1-3 confirmations, the transaction is effectively final.</li>
          </ol>
          <p>Your wallet will automatically track the transaction and update your balance. No further action required.</p>

          <h2>Sending Bitcoin: The Careful Process</h2>
          <p>Sending is where Bitcoin's irreversibility demands caution. Once you broadcast a transaction, there's no undo button. No customer service. No chargebacks. Here's how to do it right:</p>

          <ol>
            <li><strong>Get the recipient's address:</strong> Ask them for their Bitcoin address. Verify it carefully—typos send funds to the wrong person permanently.</li>
            <li><strong>Open your wallet and tap "Send":</strong> Paste the recipient's address. Most wallets let you scan a QR code instead.</li>
            <li><strong>Enter the amount:</strong> Specify how much bitcoin to send. Your wallet will show the amount in BTC and your local currency.</li>
            <li><strong>Choose a fee:</strong> Bitcoin transactions require a fee paid to miners. Higher fees = faster confirmation. More on this below.</li>
            <li><strong>Review everything twice:</strong> Check the address, the amount, and the fee. Bitcoin transactions are irreversible.</li>
            <li><strong>Confirm and broadcast:</strong> Your wallet signs the transaction with your private key and broadcasts it to the network.</li>
          </ol>

          <p>The transaction now waits in the "mempool" (memory pool) until a miner includes it in a block. Depending on your fee and network congestion, this can take minutes to hours.</p>

          <div className="key-concept">
            <div className="key-concept-label">Critical Rule</div>
            <p className="key-concept-text">Always double-check addresses before sending. Copy-paste carefully. Verify the first and last few characters. Bitcoin has no undo. A wrong address means permanent loss.</p>
          </div>

          <h2>Transaction Fees: How They Work</h2>
          <p>Bitcoin transaction fees are not fixed—they're determined by supply and demand. When the network is busy, fees rise. When it's quiet, fees drop.</p>
          <p>Fees are measured in <strong>satoshis per vbyte (sat/vB)</strong>. A satoshi is the smallest unit of bitcoin (0.00000001 BTC). A vbyte (virtual byte) measures transaction size. Larger transactions (more inputs/outputs) cost more.</p>
          <p>Most wallets offer three fee options:</p>
          <ul>
            <li><strong>Low priority:</strong> Cheap but slow (hours to days). Use for non-urgent transfers.</li>
            <li><strong>Medium priority:</strong> Moderate cost, moderate speed (30-120 minutes). The default for most transactions.</li>
            <li><strong>High priority:</strong> Expensive but fast (next block, ~10 minutes). Use for time-sensitive payments.</li>
          </ul>
          <p>To check current fee rates, visit <strong>mempool.space</strong>—a website showing the Bitcoin mempool in real-time. It recommends optimal fees based on how fast you want confirmation.</p>

          <FeeLab />

          <h2>Confirmations: When Is It Final?</h2>
          <p>A Bitcoin transaction isn't truly final until it's buried under multiple blocks. Here's what each confirmation level means:</p>
          <ul>
            <li><strong>0 confirmations (unconfirmed):</strong> Visible in the mempool but not yet in a block. Technically reversible (though rare). Don't rely on unconfirmed transactions for large amounts.</li>
            <li><strong>1 confirmation:</strong> Included in a block. The transaction is now part of the blockchain. For small amounts, this is usually enough.</li>
            <li><strong>3-6 confirmations:</strong> Standard for larger transactions. Each additional block makes reversal exponentially harder.</li>
            <li><strong>6+ confirmations:</strong> Considered irreversible by the entire ecosystem. Exchanges typically require 3-6 confirmations before crediting your account.</li>
          </ul>

          <h2>Common Mistakes (and How to Avoid Them)</h2>
          <ul>
            <li><strong>Not verifying addresses:</strong> Always check the first and last characters. Clipboard malware exists that replaces copied addresses.</li>
            <li><strong>Sending to the wrong network:</strong> Bitcoin addresses only work on the Bitcoin network. Never send bitcoin to an Ethereum address (or vice versa).</li>
            <li><strong>Using too-low fees during congestion:</strong> Your transaction could get stuck for days. Check mempool.space first.</li>
            <li><strong>Ignoring confirmations:</strong> Don't ship a product or deliver a service until the transaction has at least one confirmation (more for large amounts).</li>
            <li><strong>Reusing addresses:</strong> For privacy, generate a fresh address for each transaction. Modern wallets do this automatically.</li>
          </ul>

          <h2>Privacy Considerations</h2>
          <p>Bitcoin transactions are public. Anyone can view the blockchain, see transaction amounts, addresses involved, and timing. This doesn't reveal your identity directly—addresses aren't linked to names—but transaction patterns can be traced.</p>
          <p>Best practices for privacy:</p>
          <ul>
            <li>Use a new address for every transaction.</li>
            <li>Avoid posting your addresses publicly.</li>
            <li>Use coin control features (in advanced wallets) to avoid linking unrelated transactions.</li>
            <li>Consider privacy-focused wallets like Wasabi or Samourai (advanced topics).</li>
          </ul>

          <p>We'll explore privacy in more depth in Week 4. For now, just know: Bitcoin is pseudonymous, not anonymous. Act accordingly.</p>

          <div className="lesson-summary">
            <h3 className="summary-title">Lesson Summary</h3>
            <ul className="summary-list">
              <li>Addresses are like mailboxes—share freely, generate fresh ones for each receive</li>
              <li>Transactions include inputs, outputs, fees, and cryptographic signatures</li>
              <li>Fees vary with network congestion; check mempool.space for current rates</li>
              <li>Wait for confirmations before considering large receipts final</li>
              <li>Double-check addresses and amounts—transactions are irreversible</li>
              <li>Every transaction is public; practice basic privacy hygiene</li>
            </ul>
          </div>
    </LessonLayout>
  );
}
