import LessonLayout from '@/components/LessonLayout';

export default function BoardingPassLesson() {
  return (
    <LessonLayout slug="the-seed-phrase-your-master-key">
      <p>Your seed phrase is the single most important thing in your bitcoin life. If you remember nothing else from this course, remember this: protect your seed phrase, and you protect your bitcoin. Lose your seed phrase, and you lose everything.</p>

      <h2>What Is a Seed Phrase?</h2>
      <p>A seed phrase (also called a recovery phrase, backup phrase, or mnemonic) is a series of 12 or 24 words generated by your wallet when you first create it. These words—in this specific order—mathematically represent the master key to your entire wallet.</p>
      <p>With your seed phrase, you can restore your wallet on any compatible device. Without it, if you lose your phone, forget your password, or your device breaks, your bitcoin is gone forever. No company can help you. No support ticket can save you. The seed phrase is your only lifeline.</p>
      <p>Example seed phrase (DO NOT USE THIS—it's for illustration only):</p>
      <p><em>witch collapse practice feed shame open despair creek road again ice least</em></p>

      <h2>How Seed Phrases Work</h2>
      <p>The seed phrase is based on a technical standard called <strong>BIP39</strong> (Bitcoin Improvement Proposal 39). This standard defines a list of 2,048 carefully chosen words. Your wallet randomly selects 12 or 24 words from this list to create your seed.</p>
      <p>These words encode a very large random number—your "master seed." From this seed, your wallet can mathematically derive billions of private keys, each corresponding to a different Bitcoin address. So those 12 simple words unlock an entire universe of addresses and keys.</p>
      <p>The beauty (and danger) of this system: anyone with your seed phrase can regenerate all your private keys and thus control all your bitcoin. That's why seed phrase security is paramount.</p>

      <div className="key-concept">
        <div className="key-concept-label">Mathematical Reality</div>
        <p className="key-concept-text">A 12-word seed phrase has 2,048^12 possible combinations—that's 2^128, or approximately 340 undecillion possibilities. It's mathematically impossible to guess. But if someone steals it, they don't need to guess.</p>
      </div>

      <h2>The Golden Rules of Seed Phrase Security</h2>
      <p>These rules are absolute. Break them, and you risk losing everything.</p>

      <h3>Rule 1: Never Store It Digitally</h3>
      <p>Do not take a screenshot. Do not save it in a note app, password manager, or cloud storage. Do not email it to yourself. Do not type it into any device connected to the internet. The moment your seed phrase touches a connected device, it becomes vulnerable to hacking, malware, and data breaches.</p>

      <h3>Rule 2: Write It on Physical Media</h3>
      <p>Use pen and paper at minimum. Write clearly. Double-check every word. Store the paper somewhere secure—a safe, lockbox, or hidden location only you know about. For long-term storage, consider metal backups (products like Cryptosteel or Billfodl) that are fireproof, waterproof, and nearly indestructible.</p>

      <h3>Rule 3: Never Share It with Anyone</h3>
      <p>No legitimate company—not your wallet provider, not an exchange, not Bitcoin support—will ever ask for your seed phrase. If someone does, it's a scam. Even trusted friends and family shouldn't know your seed phrase unless you're planning inheritance (a topic for Week 4).</p>

      <h3>Rule 4: Store Multiple Backups</h3>
      <p>One backup isn't enough. What if your house burns down? What if the paper gets soaked or stolen? Store backups in separate physical locations—your home safe, a trusted family member's safe, a safety deposit box. Geographic redundancy protects against disasters.</p>

      <h3>Rule 5: Test Your Backup</h3>
      <p>After writing down your seed phrase, test it. Some people restore their wallet on a second device to confirm the backup works. Others wait until they've only deposited a small test amount. Either way, verify your backup before you trust it with serious money.</p>

      <h2>Common Seed Phrase Threats</h2>
      <p>Attackers know the seed phrase is the ultimate prize. Here are the most common attack vectors:</p>

      <ul>
        <li><strong>Phishing websites:</strong> Fake wallet sites that ask you to "verify" your wallet by entering your seed phrase. Once you do, your bitcoin is instantly stolen.</li>
        <li><strong>Fake support scams:</strong> Someone posing as customer support claims there's a problem with your wallet and asks for your seed phrase to "fix" it. Hang up. It's always a scam.</li>
        <li><strong>Physical theft:</strong> Someone breaks into your home, finds your written seed phrase, and steals your bitcoin remotely—they don't need your device, just the words.</li>
        <li><strong>Malware/keyloggers:</strong> Malicious software that records what you type or takes screenshots when you enter your seed phrase on a computer.</li>
        <li><strong>Social engineering:</strong> Attackers build trust over weeks or months, then ask for your seed phrase under a "helpful" pretext. Never fall for it.</li>
      </ul>

      <h2>Restoring a Wallet from Your Seed Phrase</h2>
      <p>If you lose your device or switch to a new wallet, you can restore everything using your seed phrase. Here's how:</p>

      <ol>
        <li>Download a compatible wallet (most wallets that support BIP39 seed phrases will work).</li>
        <li>Select "Restore from seed phrase" instead of creating a new wallet.</li>
        <li>Enter your 12 or 24 words in the correct order.</li>
        <li>The wallet scans the blockchain for all transactions associated with your seed.</li>
        <li>Your balance and transaction history reappear. You're back in business.</li>
      </ol>

      <p>This process proves a critical point: your wallet app is just a window into the blockchain. Your bitcoin isn't "stored" on your phone—it's on the blockchain, controlled by your seed phrase. The wallet app is merely a tool for accessing it.</p>

      <h2>Advanced Option: The Passphrase (25th Word)</h2>
      <p>Some advanced users add an optional <strong>passphrase</strong> (sometimes called the "25th word") to their seed phrase. This passphrase acts as a second factor—even if someone finds your seed phrase, they can't access your bitcoin without the passphrase.</p>
      <p>How it works: When you restore your wallet, you enter your seed phrase plus the passphrase. The passphrase mathematically modifies the seed, generating an entirely different set of addresses. Without the passphrase, the wallet shows zero balance (or a small "decoy" balance if you set one up).</p>
      <p><strong>Warning:</strong> If you forget your passphrase, your bitcoin is lost forever—there's no recovery. Passphrases are a powerful security tool for advanced users with large holdings, but beginners should focus on securing the seed phrase first.</p>

      <h2>Inheritance and Emergency Access</h2>
      <p>One question haunts every Bitcoin holder: what happens if I die? If no one else knows your seed phrase, your bitcoin vanishes forever. But sharing it too widely defeats the purpose of self-custody.</p>
      <p>Options for inheritance planning (we'll cover this in depth in Week 4):</p>
      <ul>
        <li>Split the seed phrase into multiple parts and give them to different trusted people (requires 2 or 3 parts to reconstruct).</li>
        <li>Use a time-locked multisig setup that requires your signature plus a backup key held by a trusted person.</li>
        <li>Store your seed phrase in a safe with instructions for access after your death.</li>
        <li>Use a professional Bitcoin custody service that offers inheritance solutions.</li>
      </ul>

      <p>The key principle: balance security (protecting your bitcoin while you're alive) with accessibility (ensuring your heirs can access it after you're gone).</p>

      <div className="lesson-summary">
        <h3 className="summary-title">Lesson Summary</h3>
        <ul className="summary-list">
          <li>Your seed phrase (12 or 24 words) generates all your keys and controls all your bitcoin</li>
          <li>Never store it digitally—paper minimum, metal preferred</li>
          <li>Never share it with anyone for any reason</li>
          <li>No legitimate service will ever ask for it</li>
          <li>Keep backups in separate physical locations</li>
          <li>Consider inheritance planning—someone needs to access this after you</li>
          <li>Passphrase option exists for advanced security (covered later)</li>
        </ul>
      </div>
    </LessonLayout>
  );
}
